import type { Metadata } from 'next';
import ShapeLandingPage, { type ShapeLandingPageData } from '@/components/storefront/ShapeLandingPage';

export const metadata: Metadata = {
  title: 'Custom Hexagon Window Shades — 6-Point Precision | World Wide Shades',
  description: 'Motorized custom hexagon shades with 6-point measurement validation. Expert-engineered for six-sided and geometric windows. 700+ fabrics, complimentary validation call.',
};

const data: ShapeLandingPageData = {
  metaTitle: 'Custom Hexagon Window Shades — 6-Point Precision | World Wide Shades',
  metaDescription: 'Motorized custom hexagon shades with 6-point measurement validation. Expert-engineered for six-sided and geometric windows.',
  shapeName: 'Hexagon',
  heroEyebrow: 'Specialty Window Solutions',
  heroTitle: 'Custom Hexagon Window Shades',
  heroTitleAccent: '— 6-Point Precision',
  heroSubtitle: 'Motorized, precision-cut shades designed specifically for hexagon windows. Six-point measurement system ensures every angle is perfect, guaranteed.',
  stat1Value: '144"',
  stat1Label: 'Max Width & Height',
  stat2Value: '700+',
  stat2Label: 'Fabric Options',
  stat3Value: '40+',
  stat3Label: 'Years Experience',
  ctaPrimaryText: 'Start Your Custom Hexagon Shade',
  heroMicrocopy1: 'Free measurement validation',
  heroMicrocopy2: 'Ships in 5–7 days',
  qualifierForTitle: 'Who This Is For',
  qualifierForText: 'Homeowners and designers with hexagon, six-sided, or geometric windows where standard shades do not fit — and six-point precision matters.',
  qualifierNotTitle: "Who It's Not For",
  qualifierNotText: 'If you are looking for a $200 off-the-shelf shade or a temporary solution, this is not the right product.',
  problemLabel: 'The Problem',
  problemTitle: 'Hexagon Windows Are Geometric Masterpieces — Until You Try to Cover Them',
  problemQuote: 'When a shade costs nearly $2,000 and has six critical measurements, guessing is not an option.',
  solutionLabel: 'The Solution',
  solutionTitle: 'A Hexagon Shade System Designed to Remove Guesswork',
  solutionSubtitle: 'Everything about our process is built to ensure your shade fits perfectly the first time — all six sides.',
  authorityHighlight: 'Our team specializes in complex geometries',
  authorityText: 'hexagons, pentagons, octagons, and architectural windows most brands refuse to make. Over 40 years of experience covering difficult openings.',
  videoLabel: 'See It In Action',
  videoTitle: 'Motorized Hexagon Operation',
  videoUrl: 'https://cdn.shopify.com/videos/c/o/v/bffc3ad9bab14c2d913b44e1cec28cba.mp4',
  videoCaption: 'Smooth, tensioned movement across all six edges — engineered for hexagon geometry.',
  shapesLabel: 'Shape Selection',
  shapesTitle: 'Choose Your Hexagon Shape',
  shapesSubtitle: 'Each hexagon configuration has its own measurement logic. We guide you through the correct one.',
  shapesHelpHighlight: 'Not sure which shape you have?',
  shapesHelpText: 'Our team helps you confirm before ordering.',
  measurementDiagramUrl: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895722/Flat_Top_Hexagon_zlqbx3.png',
  measurementLabel: 'Measurements',
  measurementTitle: 'Clear Diagrams. Guided Steps. Expert Review.',
  measurementWhatTitle: "What You'll Measure",
  measurementPromiseTitle: 'Our Promise',
  validationTitle: '6-Point Measurement Validation Included',
  validationDesc: 'After you order, we offer a complimentary validation call (Zoom or phone) to review all six measurements before production begins.',
  diagramNote: 'Our hexagon measurement guide walks you through every step with shape-specific diagrams.',
  processLabel: 'How It Works',
  processTitle: 'From Measurement to Installation',
  processNote: 'Most orders ship in 4–6 weeks. Rush production available for select configurations.',
  motorLabel: 'Motorization',
  motorTitle: "Standard Motorization — Because Hexagons Don't Work with Pull Cords",
  motorNote: 'All motors UL listed. Professional electrical consultation recommended for hardwired installations.',
  specsLabel: 'Technical Details',
  specsTitle: 'Full Technical Specifications',
  specsCol1Title: 'Specifications',
  specsCol2Title: 'Options',
  installLabel: 'Installation',
  installTitle: 'Install It Yourself — Or Let a Pro Handle Everything',
  installSubtitle: 'Choose the path that works best for your project and comfort level.',
  testimonialsLabel: 'Testimonials',
  testimonialsTitle: 'Trusted for Complex Windows Nationwide',
  proofBadgeText: 'Specialty shapes are our specialty. Hexagon shades installed in residential and architectural projects across the U.S.',
  guaranteeLabel: 'Our Guarantee',
  guaranteeTitle: "Designed to Be Right — Before It's Built",
  guaranteeNote: 'This is a guided, engineered purchase — not a roll of fabric in a box.',
  finalCtaTitle: 'Your Hexagon Window Deserves a',
  finalCtaAccent: 'Precision Solution',
  finalCtaPrimaryText: 'Start Your Custom Hexagon Shade',
  finalCtaSecondaryText: 'Talk to a Measurement Expert (Free)',
  finalCtaMicrocopy: 'No payment required to start • All 6 measurements reviewed before production',
  finalCtaNote: 'Starting at $1,950 • Motorized standard • Built to fit your exact geometry',
  painPoints: [
    'Six sides and angles that all must align precisely',
    'Standard window treatments cannot cover six-sided openings',
    'Finding anyone willing to quote hexagon shades is nearly impossible',
    'Manual cords and chains do not work on multi-angled frames',
    'DIY solutions leave gaps and look unprofessional',
  ],
  differentiators: [
    { icon: '⚡', title: 'Motorized by Default', desc: 'Smooth, even movement along all six edges. No manual pulling or uneven lifting — just effortless operation at the touch of a button.' },
    { icon: '⬡', title: 'Precision 6-Point Engineering', desc: 'Built specifically for hexagon geometry with exact engineering for all six corners and angled sides.' },
    { icon: '📐', title: 'Hexagon Measurement Guides', desc: 'Shape-specific diagrams showing exactly where to measure all six sides and critical dimensions. No guessing, no complex math.' },
    { icon: '👤', title: 'Expert Validation Call', desc: 'We review your measurements before production begins. A complimentary Zoom or phone call to ensure all six points are correct.' },
    { icon: '↕', title: '144" Max Size', desc: 'Handles dramatic architectural hexagon windows up to 144" W × 144" H. Custom engineering for larger sizes.' },
  ],
  shapeOptions: [
    { name: 'Regular Hexagon', desc: 'Six equal sides and angles', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895722/Flat_Top_Hexagon_zlqbx3.png' },
    { name: 'Elongated Hexagon', desc: 'Stretched vertically or horizontally' },
    { name: 'Irregular Hexagon', desc: 'Six sides with varying angles' },
  ],
  measurements: ['Top Width', 'Bottom Width', 'Total Height (top to bottom)', 'Upper Left Angled Side', 'Upper Right Angled Side', 'Lower Left Angled Side', 'Lower Right Angled Side', 'Window Depth (for motor clearance)'],
  promises: [
    'Clear 6-point measurement diagrams',
    'Units clearly defined (inches to 1/8")',
    'No complex math or angle calculations',
    'Expert review catches errors before production',
  ],
  processSteps: [
    { number: '1', title: 'Submit Measurements', desc: 'Use our hexagon guides or request pro help' },
    { number: '2', title: 'Validation Call', desc: 'We review all 6 dimensions before production' },
    { number: '3', title: 'Production', desc: '4–6 weeks precision manufacturing' },
    { number: '4', title: 'Installation', desc: 'DIY or professional available' },
  ],
  motorFeatures: [
    { icon: '⚡', title: 'Quiet, Reliable Motors', desc: 'Somfy motors rated for years of daily use. Ultra-quiet operation on complex multi-angle frames.' },
    { icon: '📱', title: 'Smart Home Ready', desc: 'Works with Alexa, Google Home, Control4, Lutron, and more.' },
    { icon: '🔌', title: 'Hardwire or Plug-In', desc: 'Line voltage standard. Low voltage and battery options available.' },
    { icon: '🎮', title: 'Multiple Controls', desc: 'RF remote, wall switch, app control, or voice activation.' },
  ],
  specs: [
    { column: 'specifications', label: 'Max Width', value: '144"' },
    { column: 'specifications', label: 'Max Height', value: '144"' },
    { column: 'specifications', label: 'Min Angle', value: '15°' },
    { column: 'specifications', label: 'Fabric Types', value: 'Blackout, Light Filtering, Solar' },
    { column: 'specifications', label: 'Fabric Options', value: '700+' },
    { column: 'specifications', label: 'Motor Type', value: 'Tubular, battery or AC' },
    { column: 'specifications', label: 'Warranty', value: '5 years motor, 3 years fabric' },
    { column: 'options', label: 'Motor (Standard)', value: 'Line Voltage (120V/60 Hz)' },
    { column: 'options', label: 'Motor (Optional)', value: 'Low Voltage (24VDC)' },
    { column: 'options', label: 'Control (Standard)', value: 'RF Remote, Wall Transmitter' },
    { column: 'options', label: 'Control (Optional)', value: '4-Wire / Decora Switch, Home Automation' },
    { column: 'options', label: 'Shade Box', value: 'None, 4¾" × 5", 3½" × 3½"' },
    { column: 'options', label: 'End Caps', value: 'Optional' },
    { column: 'options', label: 'Light Gap', value: '¾" – 1"' },
  ],
  installOptions: [
    {
      badge: 'DIY Path',
      title: 'Self Installation',
      desc: 'Everything you need to confidently install your hexagon shade yourself.',
      features: ['Step-by-step installation videos', 'Printed installation brochures included', 'Bracket positioning guides for 6-point frames', 'Phone support if you get stuck'],
    },
    {
      badge: 'Professional Path',
      title: 'Expert Installation',
      desc: 'Our nationwide network of vetted installers for complete peace of mind.',
      features: ['Nationwide network of vetted installers', 'Can handle measurement + installation', 'Ideal for high ceilings or complex geometries', 'Full warranty on installation'],
    },
  ],
  testimonials: [
    { text: 'Our Victorian home has original hexagon windows that we thought would never have proper shades. World Wide Shades measured all six sides perfectly. The craftsmanship is outstanding.', author: 'Patricia & Edward H.', location: 'San Francisco, CA' },
    { text: 'The six-point measurement guide made what seemed impossible completely doable. I measured it myself and the fit was absolutely perfect. Highly recommend.', author: 'Steven R.', location: 'Boston, MA' },
    { text: 'We design modern homes with geometric windows. Hexagons used to be a client nightmare — now we just call World Wide Shades. They handle everything flawlessly.', author: 'Geometric Design Associates', location: 'Austin, TX' },
  ],
  guaranteePoints: [
    '6-point measurement validation before production',
    'Expert support throughout ordering',
    'Professional measurement option available',
    'Multi-angle documentation included',
  ],
};

export default function HexagonShadesPage() {
  return <ShapeLandingPage data={data} />;
}
