import type { Metadata } from 'next';
import ShapeLandingPage, { type ShapeLandingPageData } from '@/components/storefront/ShapeLandingPage';

export const metadata: Metadata = {
  title: 'Custom Trapezoid Window Shades — Precision Engineered | World Wide Shades',
  description: 'Motorized custom trapezoid shades with 4-point measurement validation. Perfect fit for angled and architectural windows. 700+ fabrics, expert support.',
};

const data: ShapeLandingPageData = {
  metaTitle: 'Custom Trapezoid Window Shades — Precision Engineered | World Wide Shades',
  metaDescription: 'Motorized custom trapezoid shades with 4-point measurement validation. Perfect fit for angled and architectural windows.',
  shapeName: 'Trapezoid',
  heroEyebrow: 'Specialty Window Solutions',
  heroTitle: 'Custom Trapezoid Window Shades',
  heroTitleAccent: '— Precision Engineered',
  heroSubtitle: 'Motorized, precision-cut shades designed specifically for trapezoid windows. Four-point measurement system ensures a perfect fit, guaranteed.',
  stat1Value: '144"',
  stat1Label: 'Max Width & Height',
  stat2Value: '700+',
  stat2Label: 'Fabric Options',
  stat3Value: '40+',
  stat3Label: 'Years Experience',
  ctaPrimaryText: 'Start Your Custom Trapezoid Shade',
  heroMicrocopy1: 'Free measurement validation',
  heroMicrocopy2: 'Ships in 5–7 days',
  qualifierForTitle: 'Who This Is For',
  qualifierForText: 'Homeowners and designers with trapezoid, angled, or architectural windows where standard shades don\'t fit — and four-point precision matters.',
  qualifierNotTitle: "Who It's Not For",
  qualifierNotText: "If you're looking for a $200 off-the-shelf shade or a temporary solution, this isn't the right product.",
  problemLabel: 'The Problem',
  problemTitle: 'Trapezoid Windows Are Stunning — Until You Try to Cover Them',
  problemQuote: 'When a shade costs nearly $2,000 and has four critical measurements, guessing is not an option.',
  solutionLabel: 'The Solution',
  solutionTitle: 'A Trapezoid Shade System Designed to Remove Guesswork',
  solutionSubtitle: 'Everything about our process is built to ensure your shade fits perfectly the first time — all four sides.',
  authorityHighlight: 'Our team specializes in complex geometries',
  authorityText: 'trapezoids, triangles, and architectural windows most brands refuse to make. Over 40 years of experience covering difficult openings.',
  videoLabel: 'See It In Action',
  videoTitle: 'Motorized Trapezoid Operation',
  videoUrl: 'https://cdn.shopify.com/videos/c/o/v/eb6afc0512c8446b809265da98f88905.mp4',
  videoCaption: 'Smooth, tensioned movement along angled rails — engineered for trapezoid geometry.',
  shapesLabel: 'Shape Selection',
  shapesTitle: 'Choose Your Trapezoid Shape',
  shapesSubtitle: 'Each trapezoid configuration has its own measurement logic. We guide you through the correct one.',
  shapesHelpHighlight: 'Not sure which shape you have?',
  shapesHelpText: 'Our team helps you confirm before ordering.',
  measurementDiagramUrl: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895719/Trapezoid_ksy87c.png',
  measurementLabel: 'Measurements',
  measurementTitle: 'Clear Diagrams. Guided Steps. Expert Review.',
  measurementWhatTitle: "What You'll Measure",
  measurementPromiseTitle: 'Our Promise',
  validationTitle: '4-Point Measurement Validation Included',
  validationDesc: 'After you order, we offer a complimentary validation call (Zoom or phone) to review all four measurements before production begins.',
  diagramNote: 'Our trapezoid measurement guide walks you through every step with shape-specific diagrams.',
  processLabel: 'How It Works',
  processTitle: 'From Measurement to Installation',
  processNote: 'Most orders ship in 4–6 weeks. Rush production available for select configurations.',
  motorLabel: 'Motorization',
  motorTitle: "Standard Motorization — Because Trapezoids Don't Work with Pull Cords",
  motorNote: 'All motors UL listed. Professional electrical consultation recommended for hardwired installations.',
  specsLabel: 'Technical Details',
  specsTitle: 'Full Technical Specifications',
  specsCol1Title: 'Specifications',
  specsCol2Title: 'Options',
  installLabel: 'Installation',
  installTitle: 'Install It Yourself — Or Let a Pro Handle Everything',
  installSubtitle: 'Choose the path that works best for your project and comfort level.',
  testimonialsLabel: 'Testimonials',
  testimonialsTitle: 'Trusted for Complex Windows Nationwide',
  proofBadgeText: 'Specialty shapes are our specialty. Trapezoid shades installed in residential and architectural projects across the U.S.',
  guaranteeLabel: 'Our Guarantee',
  guaranteeTitle: "Designed to Be Right — Before It's Built",
  guaranteeNote: 'This is a guided, engineered purchase — not a roll of fabric in a box.',
  finalCtaTitle: 'Your Trapezoid Window Deserves a',
  finalCtaAccent: 'Precision Solution',
  finalCtaPrimaryText: 'Start Your Custom Trapezoid Shade',
  finalCtaSecondaryText: 'Talk to a Measurement Expert (Free)',
  finalCtaMicrocopy: 'No payment required to start • All 4 measurements reviewed before production',
  finalCtaNote: 'Starting at $1,950 • Motorized standard • Built to fit your exact geometry',
  painPoints: [
    'Four different measurements that all must be exact',
    'Angled sides make standard blinds impossible',
    "Most window treatment companies won't quote trapezoids",
    "Manual cords don't work on slanted rails",
    'DIY solutions create visible gaps and uneven coverage',
  ],
  differentiators: [
    { icon: '⚡', title: 'Motorized by Default', desc: 'Smooth, even movement along angled rails. No manual pulling or uneven lifting — just effortless operation at the touch of a button.' },
    { icon: '◇', title: 'Precision 4-Point Engineering', desc: 'Built specifically for trapezoid geometry with exact engineering for each of the four corners and angled sides.' },
    { icon: '📐', title: 'Trapezoid Measurement Guides', desc: 'Shape-specific diagrams showing exactly where to measure top width, bottom width, and both side heights. No guessing.' },
    { icon: '👤', title: 'Expert Validation Call', desc: 'We review your measurements before production begins. A complimentary Zoom or phone call to ensure everything is correct.' },
    { icon: '↕', title: '144" Max Size', desc: 'Handles dramatic architectural trapezoid windows up to 144" W × 144" H. Custom engineering for larger sizes.' },
  ],
  shapeOptions: [
    { name: 'Standard Trapezoid', desc: 'Wider at bottom, narrower at top', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895719/Trapezoid_ksy87c.png' },
    { name: 'Inverted Trapezoid', desc: 'Wider at top, narrower at bottom' },
    { name: 'Angled Trapezoid', desc: 'One vertical side, one angled side' },
  ],
  measurements: ['Top Width (shortest parallel side)', 'Bottom Width (longest parallel side)', 'Left Side Height', 'Right Side Height', 'Window Depth (for motor clearance)'],
  promises: [
    'Clear 4-point measurement diagrams',
    'Units clearly defined (inches to 1/8")',
    'No complex math or angle calculations',
    'Expert review catches errors before production',
  ],
  processSteps: [
    { number: '1', title: 'Submit Measurements', desc: 'Use our trapezoid guides or request pro help' },
    { number: '2', title: 'Validation Call', desc: 'We review all 4 dimensions before production' },
    { number: '3', title: 'Production', desc: '4–6 weeks precision manufacturing' },
    { number: '4', title: 'Installation', desc: 'DIY or professional available' },
  ],
  motorFeatures: [
    { icon: '⚡', title: 'Quiet, Reliable Motors', desc: 'Somfy motors rated for years of daily use. Ultra-quiet operation on angled rails.' },
    { icon: '📱', title: 'Smart Home Ready', desc: 'Works with Alexa, Google Home, Control4, Lutron, and more.' },
    { icon: '🔌', title: 'Hardwire or Plug-In', desc: 'Line voltage standard. Low voltage and battery options available.' },
    { icon: '🎮', title: 'Multiple Controls', desc: 'RF remote, wall switch, app control, or voice activation.' },
  ],
  specs: [
    { column: 'specifications', label: 'Max Width', value: '144"' },
    { column: 'specifications', label: 'Max Height', value: '144"' },
    { column: 'specifications', label: 'Min Angle', value: '15°' },
    { column: 'specifications', label: 'Fabric Types', value: 'Blackout, Light Filtering, Solar' },
    { column: 'specifications', label: 'Fabric Options', value: '700+' },
    { column: 'specifications', label: 'Motor Type', value: 'Tubular, battery or AC' },
    { column: 'specifications', label: 'Warranty', value: '5 years motor, 3 years fabric' },
    { column: 'options', label: 'Motor (Standard)', value: 'Line Voltage (120V/60 Hz)' },
    { column: 'options', label: 'Motor (Optional)', value: 'Low Voltage (24VDC)' },
    { column: 'options', label: 'Control (Standard)', value: 'RF Remote, Wall Transmitter' },
    { column: 'options', label: 'Control (Optional)', value: '4-Wire / Decora Switch, Home Automation' },
    { column: 'options', label: 'Shade Box', value: 'None, 4¾" × 5", 3½" × 3½"' },
    { column: 'options', label: 'End Caps', value: 'Optional' },
    { column: 'options', label: 'Light Gap', value: '¾" – 1"' },
  ],
  installOptions: [
    {
      badge: 'DIY Path',
      title: 'Self Installation',
      desc: 'Everything you need to confidently install your trapezoid shade yourself.',
      features: ['Step-by-step installation videos', 'Printed installation brochures included', 'Bracket positioning guides for angled rails', 'Phone support if you get stuck'],
    },
    {
      badge: 'Professional Path',
      title: 'Expert Installation',
      desc: 'Our nationwide network of vetted installers for complete peace of mind.',
      features: ['Nationwide network of vetted installers', 'Can handle measurement + installation', 'Ideal for high ceilings or complex angles', 'Full warranty on installation'],
    },
  ],
  testimonials: [
    { text: 'Our A-frame cabin has six trapezoid windows that no one could figure out. World Wide Shades nailed every single one. The validation call was incredibly thorough.', author: 'Robert & Linda M.', location: 'Lake Tahoe, CA' },
    { text: 'The four-point measurement system made it foolproof. I was nervous about measuring trapezoids, but their diagrams showed exactly what to do. Perfect fit.', author: 'David K.', location: 'Scottsdale, AZ' },
    { text: "We're a design firm that specifies these for modern homes with angled windows. The trapezoid shades are flawless and the smart home integration is seamless.", author: 'Martinez Design Studio', location: 'Miami, FL' },
  ],
  guaranteePoints: [
    '4-point measurement validation before production',
    'Expert support throughout ordering',
    'Professional measurement option available',
    'Angle-specific documentation included',
  ],
};

export default function TrapezoidShadesPage() {
  return <ShapeLandingPage data={data} />;
}
