import type { Metadata } from 'next';
import ShapeLandingPage, { type ShapeLandingPageData } from '@/components/storefront/ShapeLandingPage';

export const metadata: Metadata = {
  title: 'Custom Pentagon Window Shades — 5-Point Precision | World Wide Shades',
  description: 'Motorized custom pentagon shades with 5-point measurement validation. Expert-engineered for five-sided and architectural windows. 700+ fabrics, complimentary validation call.',
};

const data: ShapeLandingPageData = {
  metaTitle: 'Custom Pentagon Window Shades — 5-Point Precision | World Wide Shades',
  metaDescription: 'Motorized custom pentagon shades with 5-point measurement validation. Expert-engineered for five-sided and architectural windows.',
  shapeName: 'Pentagon',
  heroEyebrow: 'Specialty Window Solutions',
  heroTitle: 'Custom Pentagon Window Shades',
  heroTitleAccent: '— 5-Point Precision',
  heroSubtitle: 'Motorized, precision-cut shades designed specifically for pentagon windows. Five-point measurement system ensures every angle is perfect, guaranteed.',
  stat1Value: '288"',
  stat1Label: 'Max Width & Height',
  stat2Value: '700+',
  stat2Label: 'Fabric Options',
  stat3Value: '40+',
  stat3Label: 'Years Experience',
  ctaPrimaryText: 'Start Your Custom Pentagon Shade',
  heroMicrocopy1: 'Free measurement validation',
  heroMicrocopy2: 'Ships in 5–7 days',
  qualifierForTitle: 'Who This Is For',
  qualifierForText: 'Homeowners and designers with pentagon, five-sided, or architectural windows where standard shades do not fit — and five-point precision matters.',
  qualifierNotTitle: "Who It's Not For",
  qualifierNotText: 'If you are looking for a $200 off-the-shelf shade or a temporary solution, this is not the right product.',
  problemLabel: 'The Problem',
  problemTitle: 'Pentagon Windows Are Architectural Gems — Until You Try to Cover Them',
  problemQuote: 'When a shade costs nearly $2,000 and has five critical measurements, guessing is not an option.',
  solutionLabel: 'The Solution',
  solutionTitle: 'A Pentagon Shade System Designed to Remove Guesswork',
  solutionSubtitle: 'Everything about our process is built to ensure your shade fits perfectly the first time — all five sides.',
  authorityHighlight: 'Our team specializes in complex geometries',
  authorityText: 'pentagons, trapezoids, triangles, and architectural windows most brands refuse to make. Over 40 years of experience covering difficult openings.',
  videoLabel: 'See It In Action',
  videoTitle: 'Motorized Pentagon Operation',
  videoUrl: 'https://cdn.shopify.com/videos/c/o/v/1599972c067c48a68af294557040f8f5.mp4',
  videoCaption: 'Smooth, tensioned movement across all five edges — engineered for pentagon geometry.',
  shapesLabel: 'Shape Selection',
  shapesTitle: 'Choose Your Pentagon Shape',
  shapesSubtitle: 'Each pentagon configuration has its own measurement logic. We guide you through the correct one.',
  shapesHelpHighlight: 'Not sure which shape you have?',
  shapesHelpText: 'Our team helps you confirm before ordering.',
  measurementDiagramUrl: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895717/Pentagon_cmdrjj.png',
  measurementLabel: 'Measurements',
  measurementTitle: 'Clear Diagrams. Guided Steps. Expert Review.',
  measurementWhatTitle: "What You'll Measure",
  measurementPromiseTitle: 'Our Promise',
  validationTitle: '5-Point Measurement Validation Included',
  validationDesc: 'After you order, we offer a complimentary validation call (Zoom or phone) to review all five measurements before production begins.',
  diagramNote: 'Our pentagon measurement guide walks you through every step with shape-specific diagrams.',
  processLabel: 'How It Works',
  processTitle: 'From Measurement to Installation',
  processNote: 'Most orders ship in 4–6 weeks. Rush production available for select configurations.',
  motorLabel: 'Motorization',
  motorTitle: "Standard Motorization — Because Pentagons Don't Work with Pull Cords",
  motorNote: 'All motors UL listed. Professional electrical consultation recommended for hardwired installations.',
  specsLabel: 'Technical Details',
  specsTitle: 'Full Technical Specifications',
  specsCol1Title: 'Specifications',
  specsCol2Title: 'Options',
  installLabel: 'Installation',
  installTitle: 'Install It Yourself — Or Let a Pro Handle Everything',
  installSubtitle: 'Choose the path that works best for your project and comfort level.',
  testimonialsLabel: 'Testimonials',
  testimonialsTitle: 'Trusted for Complex Windows Nationwide',
  proofBadgeText: 'Specialty shapes are our specialty. Pentagon shades installed in residential and architectural projects across the U.S.',
  guaranteeLabel: 'Our Guarantee',
  guaranteeTitle: "Designed to Be Right — Before It's Built",
  guaranteeNote: 'This is a guided, engineered purchase — not a roll of fabric in a box.',
  finalCtaTitle: 'Your Pentagon Window Deserves a',
  finalCtaAccent: 'Precision Solution',
  finalCtaPrimaryText: 'Start Your Custom Pentagon Shade',
  finalCtaSecondaryText: 'Talk to a Measurement Expert (Free)',
  finalCtaMicrocopy: 'No payment required to start • All 5 measurements reviewed before production',
  finalCtaNote: 'Starting at $1,950 • Motorized standard • Built to fit your exact geometry',
  painPoints: [
    'Five different angles that all must align perfectly',
    'Standard blinds cannot cover five-sided openings',
    'Almost no window treatment companies will attempt pentagons',
    'Manual operation is impossible on multi-angled frames',
    'Custom quotes often come back at outrageous prices — if at all',
  ],
  differentiators: [
    { icon: '⚡', title: 'Motorized by Default', desc: 'Smooth, even movement along all five edges. No manual pulling or uneven lifting — just effortless operation at the touch of a button.' },
    { icon: '⬠', title: 'Precision 5-Point Engineering', desc: 'Built specifically for pentagon geometry with exact engineering for all five corners and angled sides.' },
    { icon: '📐', title: 'Pentagon Measurement Guides', desc: 'Shape-specific diagrams showing exactly where to measure all five sides and heights. No guessing, no complex math.' },
    { icon: '👤', title: 'Expert Validation Call', desc: 'We review your measurements before production begins. A complimentary Zoom or phone call to ensure all five points are correct.' },
    { icon: '↕', title: '144" Max Size', desc: 'Handles dramatic architectural pentagon windows up to 144" W × 144" H. Custom engineering for larger sizes.' },
  ],
  shapeOptions: [
    { name: 'Regular Pentagon', desc: 'Five equal sides and angles' },
    { name: 'House Pentagon', desc: 'Rectangle with pointed top', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895717/Pentagon_cmdrjj.png' },
    { name: 'Irregular Pentagon', desc: 'Five sides with varying angles' },
  ],
  measurements: ['Bottom Width (base of pentagon)', 'Left Side Height', 'Right Side Height', 'Left Angled Side Length', 'Right Angled Side Length', 'Window Depth (for motor clearance)'],
  promises: [
    'Clear 5-point measurement diagrams',
    'Units clearly defined (inches to 1/8")',
    'No complex math or angle calculations',
    'Expert review catches errors before production',
  ],
  processSteps: [
    { number: '1', title: 'Submit Measurements', desc: 'Use our pentagon guides or request pro help' },
    { number: '2', title: 'Validation Call', desc: 'We review all 5 dimensions before production' },
    { number: '3', title: 'Production', desc: '4–6 weeks precision manufacturing' },
    { number: '4', title: 'Installation', desc: 'DIY or professional available' },
  ],
  motorFeatures: [
    { icon: '⚡', title: 'Quiet, Reliable Motors', desc: 'Somfy motors rated for years of daily use. Ultra-quiet operation on complex multi-angle frames.' },
    { icon: '📱', title: 'Smart Home Ready', desc: 'Works with Alexa, Google Home, Control4, Lutron, and more.' },
    { icon: '🔌', title: 'Hardwire or Plug-In', desc: 'Line voltage standard. Low voltage and battery options available.' },
    { icon: '🎮', title: 'Multiple Controls', desc: 'RF remote, wall switch, app control, or voice activation.' },
  ],
  specs: [
    { column: 'specifications', label: 'Max Width', value: '144"' },
    { column: 'specifications', label: 'Max Height', value: '144"' },
    { column: 'specifications', label: 'Min Angle', value: '15°' },
    { column: 'specifications', label: 'Fabric Types', value: 'Blackout, Light Filtering, Solar' },
    { column: 'specifications', label: 'Fabric Options', value: '700+' },
    { column: 'specifications', label: 'Motor Type', value: 'Tubular, battery or AC' },
    { column: 'specifications', label: 'Warranty', value: '5 years motor, 3 years fabric' },
    { column: 'options', label: 'Motor (Standard)', value: 'Line Voltage (120V/60 Hz)' },
    { column: 'options', label: 'Motor (Optional)', value: 'Low Voltage (24VDC)' },
    { column: 'options', label: 'Control (Standard)', value: 'RF Remote, Wall Transmitter' },
    { column: 'options', label: 'Control (Optional)', value: '4-Wire / Decora Switch, Home Automation' },
    { column: 'options', label: 'Shade Box', value: 'None, 4¾" × 5", 3½" × 3½"' },
    { column: 'options', label: 'End Caps', value: 'Optional' },
    { column: 'options', label: 'Light Gap', value: '¾" – 1"' },
  ],
  installOptions: [
    {
      badge: 'DIY Path',
      title: 'Self Installation',
      desc: 'Everything you need to confidently install your pentagon shade yourself.',
      features: ['Step-by-step installation videos', 'Printed installation brochures included', 'Bracket positioning guides for 5-point frames', 'Phone support if you get stuck'],
    },
    {
      badge: 'Professional Path',
      title: 'Expert Installation',
      desc: 'Our nationwide network of vetted installers for complete peace of mind.',
      features: ['Nationwide network of vetted installers', 'Can handle measurement + installation', 'Ideal for high ceilings or complex angles', 'Full warranty on installation'],
    },
  ],
  testimonials: [
    { text: 'We have a dramatic pentagon window above our entryway that was impossible to cover. World Wide Shades measured all five points and the shade fits like it was made for it — because it was.', author: 'Christine & Mark D.', location: 'Charlotte, NC' },
    { text: 'The five-point measurement system was surprisingly simple. I was dreading this project for years, but their diagrams made it completely manageable. Perfect fit on first try.', author: 'James T.', location: 'Portland, OR' },
    { text: 'As a custom home builder, I deal with unusual window shapes constantly. Pentagon windows used to be a nightmare until I found World Wide Shades. Now I specify them for every project.', author: 'Hawkins Custom Homes', location: 'Nashville, TN' },
  ],
  guaranteePoints: [
    '5-point measurement validation before production',
    'Expert support throughout ordering',
    'Professional measurement option available',
    'Multi-angle documentation included',
  ],
};

export default function PentagonShadesPage() {
  return <ShapeLandingPage data={data} />;
}
