import type { Metadata } from 'next';
import ShapeLandingPage, { type ShapeLandingPageData } from '@/components/storefront/ShapeLandingPage';

export const metadata: Metadata = {
  title: 'Custom Triangle Window Shades — Engineered to Fit | World Wide Shades',
  description: 'Motorized custom triangle shades for angled windows. Precision measurement guides, expert validation call, 700+ fabrics. Right triangle, acute triangle, and more.',
};

const data: ShapeLandingPageData = {
  metaTitle: 'Custom Triangle Window Shades — Engineered to Fit | World Wide Shades',
  metaDescription: 'Motorized custom triangle shades for angled windows. Precision measurement guides, expert validation call, 700+ fabrics.',
  shapeName: 'Triangle',
  heroEyebrow: 'Specialty Window Solutions',
  heroTitle: 'Custom Triangle Window Shades',
  heroTitleAccent: '— Engineered to Fit',
  heroSubtitle: 'Motorized, precision-cut shades designed specifically for triangular windows. No more guessing — just a perfect fit, guaranteed.',
  stat1Value: '288"',
  stat1Label: 'Max Width & Height',
  stat2Value: '700+',
  stat2Label: 'Fabric Options',
  stat3Value: '40+',
  stat3Label: 'Years Experience',
  ctaPrimaryText: 'Start Your Custom Triangle Shade',
  heroMicrocopy1: 'Free measurement validation',
  heroMicrocopy2: 'Ships in 5–7 business days',
  qualifierForTitle: 'Who This Is For',
  qualifierForText: 'Homeowners, architects, and designers with angled or triangular windows where standard shades fail — and a precision-engineered, permanent solution is required.',
  qualifierNotTitle: "Who It's Not For",
  qualifierNotText: "If you're looking for a low-cost, mass-produced, or temporary fix, this is not the right product.",
  problemLabel: 'The Problem',
  problemTitle: 'Triangle Windows Are Beautiful — Until You Try to Cover Them',
  problemQuote: 'When a shade costs nearly $2,000, guessing is not an option.',
  solutionLabel: 'The Solution',
  solutionTitle: 'A Triangle Shade System Designed to Remove Guesswork',
  solutionSubtitle: 'Everything about our process is built to ensure your shade fits perfectly the first time.',
  authorityHighlight: 'Our team specializes in complex geometries',
  authorityText: 'triangles, trapezoids, and architectural windows most brands refuse to make. Over 40 years of experience covering difficult openings.',
  videoLabel: 'See It In Action',
  videoTitle: 'Bottom-Up Motorized Operation',
  videoUrl: 'https://cdn.shopify.com/videos/c/o/v/09a8af75217b4a89a56275d969ac2755.mp4',
  videoCaption: 'Smooth, tensioned bottom-up motion — engineered for angled rails and large spans.',
  shapesLabel: 'Shape Selection',
  shapesTitle: 'Choose Your Triangle Shape',
  shapesSubtitle: 'Each triangle configuration has its own measurement logic. We guide you through the correct one.',
  shapesHelpHighlight: 'Not sure which shape you have?',
  shapesHelpText: 'Our team helps you confirm before ordering.',
  measurementDiagramUrl: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895723/Right_Triangle_Right_ewqoan.png',
  measurementLabel: 'Measurements',
  measurementTitle: 'Clear Diagrams. Guided Steps. Expert Review.',
  measurementWhatTitle: "What You'll Measure",
  measurementPromiseTitle: 'Our Promise',
  validationTitle: 'Measurement Validation Included',
  validationDesc: 'After you order, we offer a complimentary validation call (Zoom or phone) to review measurements before production begins.',
  diagramNote: 'Our measurement guide walks you through every step with shape-specific diagrams.',
  processLabel: 'How It Works',
  processTitle: 'From Measurement to Installation',
  processNote: 'Most orders ship in 4–6 weeks. Rush production available for select configurations.',
  motorLabel: 'Motorization',
  motorTitle: "Standard Motorization — Because Triangles Don't Work with Pull Cords",
  motorNote: 'All motors UL listed. Professional electrical consultation recommended for hardwired installations.',
  specsLabel: 'Technical Details',
  specsTitle: 'Full Technical Specifications',
  specsCol1Title: 'Specifications',
  specsCol2Title: 'Options',
  installLabel: 'Installation',
  installTitle: 'Install It Yourself — Or Let a Pro Handle Everything',
  installSubtitle: 'Choose the path that works best for your project and comfort level.',
  testimonialsLabel: 'Testimonials',
  testimonialsTitle: 'Trusted for Complex Windows Nationwide',
  proofBadgeText: 'Specialty shapes are our specialty. Used in residential and architectural projects across the U.S.',
  guaranteeLabel: 'Our Guarantee',
  guaranteeTitle: 'Designed to Be Right — Before It\'s Built',
  guaranteeNote: 'This is a guided, engineered purchase — not a roll of fabric in a box.',
  finalCtaTitle: 'Your Triangle Window Deserves a',
  finalCtaAccent: 'Precision Solution',
  finalCtaPrimaryText: 'Start Your Custom Triangle Shade',
  finalCtaSecondaryText: 'Talk to a Measurement Expert (Free)',
  finalCtaMicrocopy: 'No payment required to start • Measurements reviewed before production',
  finalCtaNote: 'Starting at $1,950 • Motorized standard • Built to fit your exact geometry',
  painPoints: [
    "Off-the-shelf shades don't fit angled glass",
    'One wrong measurement = expensive mistake',
    'Installers hesitate on non-standard shapes',
    'Manual operation is awkward or impossible',
    'Most brands simply say "we don\'t do triangles"',
  ],
  differentiators: [
    { icon: '⚡', title: 'Motorized by Default', desc: 'Smooth, even movement on angled rails. No manual tugging or uneven lifting — just effortless operation at the touch of a button.' },
    { icon: '◇', title: 'Precision Geometry', desc: 'Built specifically for Right Triangle (Left & Right), Triangle, and Triangle Top shapes with exact engineering for each configuration.' },
    { icon: '📐', title: 'Exact Measurement Diagrams', desc: 'Shape-specific, visual, and foolproof guides that show you exactly where and what to measure. No math required.' },
    { icon: '👤', title: 'Expert Validation Call', desc: 'We review your measurements before production begins. A complimentary Zoom or phone call to ensure everything is correct.' },
    { icon: '↕', title: '144" Max Size', desc: 'Handles dramatic architectural windows up to 144" W × 144" H. Larger sizes available with custom engineering.' },
  ],
  shapeOptions: [
    { name: 'Right Triangle Right', desc: '90° angle at right corner', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895723/Right_Triangle_Right_ewqoan.png' },
    { name: 'Acute Triangle', desc: 'Symmetrical triangle', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895721/Acute_Triangle_tlw47x.png' },
    { name: 'Right Triangle Left', desc: '90° angle at left corner', image: 'https://res.cloudinary.com/dcmlcfynd/image/upload/v1764895716/Right_Triangle_left_gcmcpz.png' },
  ],
  measurements: ['Left Height', 'Right Angle Length', 'Bottom Width'],
  promises: [
    'Every shape shows exactly where to measure',
    'Units clearly defined',
    'No math required',
    'No assumptions',
  ],
  processSteps: [
    { number: '1', title: 'Submit Measurements', desc: 'Use our guides or request pro help' },
    { number: '2', title: 'Validation Call', desc: 'We review before production' },
    { number: '3', title: 'Production', desc: '4–6 weeks precision build' },
    { number: '4', title: 'Installation', desc: 'DIY or professional available' },
  ],
  motorFeatures: [
    { icon: '⚡', title: 'Quiet, Reliable Motors', desc: 'Somfy motors rated for years of daily use. Ultra-quiet operation.' },
    { icon: '📱', title: 'Smart Home Ready', desc: 'Works with Alexa, Google Home, Control4, Lutron, and more.' },
    { icon: '🔌', title: 'Hardwire or Plug-In', desc: 'Line voltage standard. Low voltage and battery options available.' },
    { icon: '🎮', title: 'Multiple Controls', desc: 'RF remote, wall switch, app control, or voice activation.' },
  ],
  specs: [
    { column: 'specifications', label: 'Max Width', value: '144"' },
    { column: 'specifications', label: 'Max Height', value: '144"' },
    { column: 'specifications', label: 'Min Angle', value: '20°' },
    { column: 'specifications', label: 'Fabric Types', value: 'Blackout, Light Filtering, Solar' },
    { column: 'specifications', label: 'Fabric Options', value: '700+' },
    { column: 'specifications', label: 'Motor Type', value: 'Tubular, battery or AC' },
    { column: 'specifications', label: 'Warranty', value: '5 years motor, 3 years fabric' },
    { column: 'options', label: 'Motor (Standard)', value: 'Line Voltage (120V/60 Hz)' },
    { column: 'options', label: 'Motor (Optional)', value: 'Low Voltage (24VDC)' },
    { column: 'options', label: 'Control (Standard)', value: 'RF Remote, Wall Transmitter' },
    { column: 'options', label: 'Control (Optional)', value: '4-Wire / Decora Switch, Home Automation' },
    { column: 'options', label: 'Shade Box', value: 'None, 4¾" × 5", 3½" × 3½"' },
    { column: 'options', label: 'End Caps', value: 'Optional' },
    { column: 'options', label: 'Light Gap', value: '¾" – 1"' },
  ],
  installOptions: [
    {
      badge: 'DIY Path',
      title: 'Self Installation',
      desc: 'Everything you need to confidently install your triangle shade yourself.',
      features: ['Step-by-step installation videos', 'Printed installation brochures included', 'Designed for accuracy and alignment', 'Phone support if you get stuck'],
    },
    {
      badge: 'Professional Path',
      title: 'Expert Installation',
      desc: 'Our nationwide network of vetted installers for complete peace of mind.',
      features: ['Nationwide network of vetted installers', 'Can handle measurement + installation', 'Ideal for high ceilings or large spans', 'Full warranty on installation'],
    },
  ],
  testimonials: [
    { text: "We had a 16-foot triangle window that three other companies said they couldn't do. World Wide Shades not only made it happen, but the validation call caught a measurement error before production.", author: 'Michael R.', location: 'Denver, CO' },
    { text: 'The motorization is absolutely essential for our cathedral ceiling. No way we could have done manual. The shade operates perfectly and the remote makes it effortless.', author: 'Sarah & Tom K.', location: 'Austin, TX' },
    { text: "As an architect, I've specified these for multiple projects. The measurement diagrams are the best I've seen, and my clients love the smart home integration.", author: 'Jennifer L., AIA', location: 'Seattle, WA' },
  ],
  guaranteePoints: [
    'Measurement validation before production',
    'Expert support throughout ordering',
    'Professional measurement option available',
    'Clear documentation included',
  ],
};

export default function TriangleShadesPage() {
  return <ShapeLandingPage data={data} />;
}
